<div class="padded">
    <dt>URL:</dt>
    <dd><a href="http://<?=$this->id?>.bookingbat.com" target="_blank"><?=$this->id?>.bookingbat.com</a></dd>
    <dt>Username:</dt>
    <dd>admin</dd>
    <dt>Password:</dt>
    <dd><?=$this->escape($this->password)?></dd>
</div>

<!-- Google Code for booking bat signed up trial Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 1037534136;
    var google_conversion_language = "en";
    var google_conversion_format = "3";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "l1XlCJq-9AQQuIfe7gM";
    var google_conversion_value = 0;
    /* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/1037534136/?value=0&amp;label=l1XlCJq-9AQQuIfe7gM&amp;guid=ON&amp;script=0"/>
    </div>
</noscript>
