<div id="self-service" class="feature">
    <a href="/screenshots/calendar.png" class="thumbnail thumbnail-right" style="width:300px">
        <img src="/screenshots/calendar_small.png" />
    </a>

    <h1>Self Service Scheduling</h1>

    <p>Allow your customers to <strong>schedule appointments</strong> without calling you. Your website does the work so you don't have to. Simply set up the availability for your staff &amp; services.</strong></p>

    <p>Clients can go online &amp; browse your calendar. You may restrict them from browsing or booking appointments too far in advance. Your calendar is <strong>color coded</strong> so clients can distinguish between an off-day and a fully-booked day. Show off how popular your services are!</p>

    <p>Clients can choose to view availability for a <strong>particular staff member</strong>, or all staff members at once.</p>

</div>

<div id="multiple-staff" class="feature">
    <a href="/screenshots/staff.png" class="thumbnail thumbnail-right" style="width:300px">
        <img src="/screenshots/staff_small.png" />
    </a>
    <h1>Multiple Staff Logins</h1>
    <p>Each staff member gets their own log in, so they can <strong>manage their own appointments</strong> &amp; availability. Staff members simply log in, and set their availability times. They then get email alerts when clients book an appointment, and can view &amp; <strong>manage their own appointments.</strong></p>
</div>

<div id="mobile-friendly" class="feature">
    <a href="/screenshots/mobile.png" class="thumbnail thumbnail-right" style="width:300px">
        <img src="/screenshots/mobile_small.png" />
    </a>
    <h1>Mobile Friendly</h1>
    <p>Access <strong>all features</strong> from your mobile device. There is no stripped down "mobile version", instead the website automatically <strong>adjusts to any screen size</strong>. You can test this by doing our free trial, and viewing how the calendar changes instantly when you resize your window.</p>

</div>

<div id="settings" class="feature">
    <h1>Email Alerts</h1>
    <p>Staff & Clients get an email when an appointment is booked.</p>
</div>

<div id="settings" class="feature">
    <h1>Settings</h1>
    <p>Customize padding times between appointments, allowed appointment lengths, minimum appointment lengths &amp; more.</p>
</div>