<div id="self-service" class="feature">
    <h1>Self Service Scheduling</h1>
    <p>Allow your customers to schedule appointments without calling you. Your website does the work so you don't have to.</p>
</div>

<div id="multiple-staff" class="feature">
    <h1>Multiple Staff Logins</h1>
    <p>Each staff member gets their own log in, so they can manage their own appointments &amp; availability</p>
</div>

<div id="mobile-friendly" class="feature">
    <h1>Mobile Friendly</h1>
    <p>Access all website features from your mobile device.</p>
</div>