<div id="self-service" class="feature">
    <a href="#" class="thumbnail thumbnail-right" style="width:300px">
        <img src="/screenshots/calendar_small.png" />
    </a>

    <h1>Self Service Scheduling</h1>

    <p>Allow your customers to <strong>schedule appointments</strong> without calling you. Your website does the work so you don't have to. Simply set up the availability for your staff &amp; services.</strong></p>

    <p>Clients can go online &amp; browse your calendar. You may restrict them from browsing or booking appointments too far in advance. Your calendar is <strong>color coded</strong> so clients can distinguish between an off-day and a fully-booked day. Show off how popular your services are!</p>

    <p>Clients can choose to view availability for a <strong>particular staff member</strong>, or all staff members at once.</p>

</div>

<div id="multiple-staff" class="feature">
    <h1>Multiple Staff Logins</h1>
    <p>Each staff member gets their own log in, so they can manage their own appointments &amp; availability</p>
</div>

<div id="mobile-friendly" class="feature">
    <h1>Mobile Friendly</h1>
    <p>Access all website features from your mobile device.</p>
</div>