<div class="padded">
    <div class="row-fluid">
        <div class="span12">
            <div class="hero-unit" style="position:relative">
                <h1>Online Appointment Booking</h1>

                <p>Booking Bat allows you to take appointments from your website. Allow your customers to schedule appointments with Booking Bat!</p>

                <a href="http://github.com/bookingbat/application"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
            </div>
        </div>
    </div>

    <div class="row-fluid sales-pitch">
        <i class="icon-calendar icon-large"></i>
        <h2>Accept Appointments</h2>
        <p>Start accepting appointments online now. <strong>Seriously</strong>, right now. No installation required, just <a href="<?=$this->url(array(),'free-trial',true)?>">sign up for a free trial</a> and you're ready to go!</p>

        <i class="icon-mobile-phone icon-large"></i>
        <h2>Mobile Friendly</h2>
        <p>Manage your schedule &amp; allow your clients to <strong>book appointments</strong> from their mobile devices - tablets, phones, or whatever the kids are using to get online these days.</p>

        <i class="icon-github icon-large"></i>
        <h2>Open Source</h2>
        <p>Did we mention <strong>its free</strong>? Fork us, we are developer friendly! Modify the look &amp; feel of your website by downloading the code to your server &amp; editing it. Custom development is always available - whether you have us do it or do it yourself.</p>

        <i class="icon-cloud icon-large"></i>
        <h2>Hosted</h2>
        <p>Not technically savvy?. No problem, let us host it for you. Pay us a reasonable monthly fee and we'll host it in the cloud and do all the technical mumbo jumbo so you can focus on what you do best - running your business.</p>
    </div>

    <a class="btn btn-primary btn-large" href="<?=$this->url(array(),'features',true)?>">Tour &amp; Features <i class="icon-arrow-right"></i></a>
</div>
