<div class="padded sales-pitch">
    <div class="row-fluid">
        <div class="span12">
            <div class="hero-unit" style="position:relative">
                <h1>Online Appointment Booking</h1>

                <p>Booking Bat allows you to take appointments from your website. Allow your customers to schedule appointments with Booking Bat!</p>

                <a href="http://github.com/bookingbat/application"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub"></a>
            </div>
        </div>
    </div>

    <div class="row-fluid">
        <div class="span8">
            <div class="row-fluid">
                <div class="span6">
                    <i class="icon-calendar icon-large"></i>
                    <h2>Accept Appointments</h2>
                    <p>Start accepting appointments online now. <strong>No installation</strong> required, just <a href="<?=$this->url(array(),'free-trial',true)?>">sign up for a free trial</a> and you're ready to go!</p>

                    <i class="icon-mobile-phone icon-large"></i>
                    <h2>Mobile Friendly</h2>
                    <p>Manage your schedule &amp; allow your clients to <strong>book appointments</strong> from their mobile devices.</p>
                </div>
                <div class="span6">
                    <i class="icon-cloud icon-large"></i>
                    <h2>Hosted</h2>
                    <p>We'll host it in the cloud and do all the technical mumbo jumbo so you can focus on what you do best - running your business.</p>

                    <i class="icon-github icon-large"></i>
                    <h2>Open Source</h2>
                    <p>Did we mention <strong>its free</strong>? Modify the look &amp; feel of your website by downloading the code to your server &amp; editing it. Custom development is always available - whether you have us do it or do it yourself.</p>


                </div>
            </div>

            <div class="row-fluid">
                <div class="span6">
                    <a class="btn btn-large" href="<?=$this->url(array(),'features',true)?>">Tour &amp; Features <i class="icon-arrow-right"></i></a>
                </div>
                <div class="span6">
                    <a class="btn btn-primary btn-large" href="<?=$this->url(array(),'free-trial',true)?>">Free Trial <i class="icon-arrow-right"></i></a>
                </div>
            </div>
        </div>

        <div class="span4">
            <a href="/screenshots/mobile.png" class="thumbnail">
                <img src="/screenshots/mobile_small.png" />
            </a>

        </div>
    </div>




</div>
