<div class="home">
    <div class="row-fluid">
        <div class="span12">
            <div class="hero-unit">
                <h1>Online Appointment Booking Software For Your Business</h1>

                <p>Booking Bat allows you to take appointments from your website. Allow your customers to schedule appointments with Booking Bat.</p>
            </div>
        </div>
    </div>

    <div class="row-fluid sales-pitch">
        <div class="span6">
            <i class="icon-calendar icon-large"></i>
            <h2>Accept Appointments</h2>
            <p>Start accepting appointments online now.</p>
        </div>
        <div class="span6">
            <i class="icon-mobile-phone icon-large"></i>
            <h2>Mobile Friendly</h2>
            <p>Manage your schedule and allow your customers to book appointments on the go</p>
        </div>
    </div>
    <div class="row-fluid sales-pitch">
        <div class="span6">
            <i class="icon-bar-chart icon-large"></i>
            <h2>Unlimited Growth</h2>
            <p>Unlimited staff, unlimited appointments</p>
        </div>
        <div class="span6">
            <i class="icon-question icon-large"></i>
            <h2>Customer Support</h2>
            <p>Backed by helpful support</p>
        </div>
    </div>
</div>
