<a id="free-trial-button" class="btn btn-primary" href="<?=$this->url(array(),'free-trial',true)?>">Try Booking Bat Free</a>
<style type="text/css">
    #free-trial-button {
        margin:auto;
        display: block;
        width:200px;
    }

    #container {
        width: 780px;
        margin:auto;
        margin-top: 100px;
        height:600px;
    }

        /*Top Bar*/
    .top {
        width: 250px; height: 50px;
        background: #2F2E35;
        -webkit-border-radius: 10px 10px 0 0;
        -moz-border-radius: 10px 10px 0 0;
        border-radius: 10px 10px 0 0;
    }

    .top h2 {
        color: #fff;
        text-align: center;
        margin:0;
        font: 300 30px/50px Helvetica, Verdana, sans-serif;
    }

        /*Shape*/
    .pricingtable {
        width: 250px; height: 375px;
        background: white;
        margin: 5px;
        float: left;
        font-size:12px;

        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;
        -webkit-box-shadow: 2px 2px 9px rgba(0,0,0,0.3);
        -moz-box-shadow: 2px 2px 9px rgba(0,0,0,0.3);
        box-shadow: 2px 2px 9px rgba(0,0,0,0.3);
    }

        /*Features*/
    .pricingtable ul {
        list-style-type: none;
        margin: 10px 0 0 35px;
    }

    .pricingtable ul strong {
        font-weight: bold;
    }

        /*Dividing Line*/
    .pricingtable hr {
        border: 0;
        background-color: #BCBEC0;
        color: #BCBEC0;
        height: 1px;
        width: 190px;
        margin: 10px 0 0 30px;
    }

        /*Price*/
    .pricingtable h1 {
        text-align: center;
        font: bold 88px/1 Helvetica, Verdana, sans-serif;
        margin: 20px 0 0 0;
    }

    .pricingtable h1 sup {
        font-size: 45px;
    }

    .pricingtable p {
        text-align: center;
        font: 500 14px/1 Helvetica, Verdana, sans-serif;
        color: #BCBEC0;
    }

        /*Button*/
    .pricingtable a {
        display: block;
        width: 150px;
        height:40px;
        line-height: 40px;
        margin: auto;
        text-transform: uppercase;
        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;
    }
        /*Scaled Version*/
    .featured {
        -webkit-transform: scale(1.2, 1.2);
        -moz-transform: scale(1.2, 1.2);
        -o-transform: scale(1.2, 1.2);
        -ms-transform: scale(1.2, 1.2);
        transform: scale(1.2, 1.2);
    }
</style>

<div id="container">
    <div class="pricingtable">
        <div class="top">
            <h2>Free Trial</h2>
        </div>
        <ul>
            <li>Hosted On Our Server</li>
            <li><strong>Unlimited</strong> Staff Login</li>
            <li><strong>Unlimited</strong> Services</li>
            <li><strong>Unlimited</strong> Appointments</li>
        </ul>

        <hr />

        <h1><sup>Free</sup></h1>
        <p>30 Day Free Trial</p>

        <a class="btn btn-success" href="<?=$this->url(array(),'free-trial',true)?>">Sign Up</a>
    </div>

    <div class="pricingtable featured">
        <div class="top">
            <h2>Hosted</h2>
        </div>
        <ul>
            <li>Hosted On Our Server</li>
            <li><strong>Unlimited</strong> Staff Logins</li>
            <li><strong>Unlimited</strong> Services</li>
            <li><strong>Unlimited</strong> Appointments</li>
        </ul>

        <hr />

        <h1><sup>$</sup>25</h1>
        <p>per month</p>

        <a class="btn btn-success" href="<?=$this->url(array(),'signup',true)?>">Sign Up</a>
    </div>

    <div class="pricingtable">
        <div class="top">
            <h2>Open Source</h2>
        </div>
        <ul>
            <li>Hosted On Your Server</li>
            <li><strong>Unlimited</strong> Staff Logins</li>
            <li><strong>Unlimited</strong> Services</li>
            <li><strong>Unlimited</strong> Appointments</li>
        </ul>

        <hr />

        <h1><sup>Free</sup></h1>
        <p>Open Source</p>

        <a class="btn btn-success" href="#">Download</a>
    </div>

</div>
