<style type="text/css">
    .signup {
        margin:auto;
        background: white;
        font-size:12px;
        width:600px;

        -webkit-border-radius: 10px;
        -moz-border-radius: 10px;
        border-radius: 10px;
        -webkit-box-shadow: 2px 2px 9px rgba(0,0,0,0.3);
        -moz-box-shadow: 2px 2px 9px rgba(0,0,0,0.3);
        box-shadow: 2px 2px 9px rgba(0,0,0,0.3);
    }
    .signup .zend_form {
        padding-left:25px;
    }

    .signup ul {
        margin-top:25px;
        list-style: none;
    }

    ul.errors {
        margin:0;
    }

    .signup li {
        margin-bottom:10px;
    }

    .top {
        width: 600px; height: 50px;
        background: #2F2E35;
        -webkit-border-radius: 10px 10px 0 0;
        -moz-border-radius: 10px 10px 0 0;
        border-radius: 10px 10px 0 0;
    }
    .top h2 {
        color: #fff;
        text-align: center;
        margin:0;
        font: 300 30px/50px Helvetica, Verdana, sans-serif;
    }
</style>

<div class="signup">
    <div class="top"><h2>Create Your Website</h2></div>
    <div class="row-fluid">
        <div class="span6">
            <form action="?" method="post">
                <dl class="zend_form">
                <?php
                echo $this->form->owner_name;
                echo $this->form->business_name;
                echo $this->form->website;
                echo $this->form->phone;
                echo $this->form->email;
                ?>
                <dt></dt>
                <dd>
                    <input type="submit" value="Get Started" class="btn btn-primary" style="padding-right:25px;" />
                    <i class="icon-arrow-right" style="margin-left:-20px;color:white;"></i>
                </dd>
                </dl>
            </form>
        </div>
        <div class="span6">
            <ul>
                <li><i class="icon-ok"></i> 100% Free</li>
                <li><i class="icon-ok"></i> Take Appointments Online</li>
                <li><i class="icon-ok"></i> Grow your business</li>
            </ul>
        </div>
    </div>
</div>