<style type="text/css">
    img {
        max-width:600px;
        display: block;
        border:1px #000 solid;
        border-radius:10px;
    }
</style>
<div class="padded">
    <div class="row-fluid">
        <div class="span4">
            <ul class="well affix">
                <li><a href="<?=$this->url(array('page'=>'create-website'))?>">Create Your Website</a></li>
                <li>Admin
                    <ul>
                        <li><a href="<?=$this->url(array('page'=>'logging-in'))?>">Logging In</a></li>
                        <li><a href="<?=$this->url(array('page'=>'manage-services'))?>">Manage Services</a></li>
                        <li><a href="<?=$this->url(array('page'=>'manage-staff'))?>">Manage Staff</a></li>
                        <li><a href="<?=$this->url(array('page'=>'manage-availability'))?>">Set Availability</a></li>
                        <li><a href="<?=$this->url(array('page'=>'assign-services'))?>">Assign Services</a></li>
                        <li><a href="<?=$this->url(array('page'=>'appointments'))?>">Appointments</a></li>
                    </ul>
                </li>
                <li>Appointments</li>
                <ul>
                    <li><a href="<?=$this->url(array('page'=>'select-service'))?>">Selecting A Service</a></li>
                    <li><a href="<?=$this->url(array('page'=>'select-date'))?>">Selecting A Date</a></li>
                    <li><a href="<?=$this->url(array('page'=>'select-duration'))?>">Select Appointment Duration</a></li>
                    <li><a href="<?=$this->url(array('page'=>'select-start'))?>">Select Appointment Start Time</a></li>
                    <li><a href="<?=$this->url(array('page'=>'select-staff'))?>">Select Staff</a></li>
                    <li><a href="<?=$this->url(array('page'=>'submit-contact-info'))?>">Submit Your Contact Information</a></li>
                    <li><a href="<?=$this->url(array('page'=>'confirmation'))?>">Confirmation</a></li>
                </ul>
                </li>
                <li>Staff
                    <ul>
                        <li><a href="<?=$this->url(array('page'=>'my-appointments'))?>">My Appointments</a></li>
                        <li><a href="<?=$this->url(array('page'=>'my-availability'))?>">My Availability</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="span8">
            <?php
            if($this->page) {
                echo $this->partial("user-guide/$this->page.phtml");
            }
            ?>
        </div>
    </div>

</div>