<!doctype html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">

    <title>Booking Bat</title>

    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/bootstrap-responsive.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.css">

    <?=$this->headLink()?>
</head>

<body>
<?=$this->partial('navigation-container.phtml')?>
<div class="container-fluid">
    <?=$this->partial('messages.phtml')?>
    <?=$this->layout()->content?>
</div>

<footer>
    &copy; 2013 BookingBat
</footer>

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-41952014-1', 'bookingbat.com');
    ga('send', 'pageview');

</script>
<script type="text/javascript" src="/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.js"></script>

</body>
</html>