<!doctype html>

<head>
    <meta charset="utf-8">

    <title>Booking Bat</title>

    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/bootstrap-responsive.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/font-awesome/css/font-awesome.css">

    <?=$this->headLink()?>
</head>

<body>
<?=$this->partial('navigation-container.phtml')?>
<div class="container-fluid">
    <?=$this->partial('messages.phtml')?>
    <?=$this->layout()->content?>
    <script src="/js/bootstrap.js"></script>
</div>

<footer>
    &copy; 2013 BookingBat
</footer>
</body>
</html>