<div class="navbar" navbar-inverse navbar-fixed-top>
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="brand" href="/">Booking Bat</a>
            <div class="nav-collapse collapse">


                <ul class="nav nav-pills pull-right">
                    <?=$this->partial('navigation.phtml')?>
                </ul>

            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>