<?php
$user = bootstrap::getInstance()->getUser();

switch ($user['type']) {
    default:
        ?>
        <li><a href="<?=$this->url(array(),'features',true)?>">Tour &amp; Features</a></li>
        <li><a href="<?=$this->url(array(),'pricing',true)?>">Pricing</a></li>
        <li><a class="trial" href="<?=$this->url(array(),'free-trial',true)?>">Free Trial</a></li>
        <li><a href="<?=$this->url(array(),'user-guide',true)?>">User Guide</a></li>
        <li><a href="<?=$this->url(array(),'contact',true)?>">Contact Us</a></li>
        <?php
        break;
}
?>