<h1>Logging In</h1>

<p>The admin login is how you will set up your website, configure availability, add staff &amp; review appointments.</p>

<img src="/img/user-guide/4.png" />
<p>Upon accessing the URL to your website, click on 'Log In' in the upper right hand corner.</p>

<img src="/img/user-guide/5.png" />
<p>You will be prompted for your admin username &amp; password. You set these up in the previous step.</p>

<img src="/img/user-guide/6.png" />
<p>Upon logging in you will see new navigation items in the top nav bar.</p>