<h1>Assign Services</h1>
<p>In order to start taking appointments, you will need to assign some services to your staff. </p>

<img src="/img/user-guide/11.png" />
<p>From the "Manage Users" page, click "Services".</p>

<img src="/img/user-guide/20.png" />
<p>You will be shown all services your business offers. Check off which ones this staff member can provide.</p>

<img src="/img/user-guide/21.png" />
<p>After you have selected the service(s) the staff member provides, click "Update Services" to save the information.</p>

<img src="/img/user-guide/22.png" />
<p>You will be shown a confirmation message that the services have been assigned to the staff.</p>