<h1>Signup for cloud instance/free trial</h1>

<p>The fastest &amp; easiest way to get started accepting appointments online is to create an instance of our "cloud" hosted solution.</p>

<img src="/img/user-guide/2.png" />
<p>To create your website, click on 'Free Trial' on the Booking Bat website. You will be prompted for your information.</p>


<img src="/img/user-guide/3.png" />
<p>Upon completing this, you will be given the admin credentials for your website. Save these in a safe place.</p>
