<h2>Manage Availability</h2>

<p>This is how you will set the hours a staff member is available to take appointments during. This is typically the staff members's scheduled working hours.</p>

<img src="/img/user-guide/11.png" />
<p>Click on "Manage Staff". You will see all staff members in the system. Click on "Availability" for the staff member you wish to edit the availability for.</p>

<img src="/img/user-guide/12.png" />
<p>On this page you will see that the staff is currently not available on any day. On the left hand side you can add some new availability hours.</p>

<img src="/img/user-guide/13.png" />
<p>Pick the day you wish to add hours of availability on. Choose the start &amp; end time for the current hours of availability. If the staff member is available from 9am-5pm, but has a 1hr lunch at 12pm, you would have to put this in as "available from 9am-12pm, and from 1pm to 5pm" (You would have to put in two periods of availability for the same day, repeating this step twice.</p>

<img src="/img/user-guide/14.png" />
<p>Upon pressing "Add" you will be shown a green confirmation message confirming the hours have been added to the staff member. You can continue to add more availability for this day, or other days, or other staff members. Just repeat the above steps as appropriate.</p>

<p>You will also notice that where it shows the staff member's availability you have the option to delete that period of availability. If there are new hours, you must delete the old hours &amp; add the new hours.</p>