<h1>Manage Staff</h1>

<p>Manage staff is where you can enter your staff/employees. Staff are assigned to services, and have "hours" of availability.</p>

<img src="/img/user-guide/7.png" />
<p>Upon clicking on "Manage Staff" you will be shown an empty table indicating there are no staff yet added. Click on "New User" to add new staff now.</p>

<img src="/img/user-guide/8.png" />
<p>You will be prompted for the staff member's information, such as username, password, &amp; contact information. Fill that out with the desired information. You will be asked to type the password twice to verify it.</p>

<img src="/img/user-guide/9.png" />
<p>After you have filled out the staff information, press "save" to create the staff member's user account.</p>

<img src="/img/user-guide/10.png" />
<p>Upon pressing "save" you will be shown a confirmation message confirming that the staff's user account has been added.</p>