<h2>Manage Services</h2>
<p>Manage Services is where you can add new &amp; manage existing services. These are the services you offer which staff are assigned to and clients can book appointments for. For this example, we'll add a new service called "Personal Training"</p>

<img src="/img/user-guide/15.png" />
<p>Upon clicking "Manage Services" you will see there are no services yet added. Click the "New Service" button</p>

<img src="/img/user-guide/16.png" />
<p>You are prompted for the service name</p>

<img src="/img/user-guide/17.png" />
<p>Fill out the service's name &amp; click "Add Service"</p>

<img src="/img/user-guide/18.png" />
<p>You get a green confirmation message confirming the service has been added, and the service is shown. From here you can repeat these steps to add more services that you offer, and/or click the pencil icon to edit an existing service's name.</p>
